---
title: "flat_regress_dataset.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(stats)
library(broom)
library(readr)
library(DT)
library(knitr)
library(yesno)
library(sjPlot)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# `regress_dataset()` : Make a linear regression on the dataset

```{r function-regress_dataset}
#' regress_dataset
#' 
#' @param data data.frame The dataset to perform regression on, must have "x" and "y" numerical column
#' @param view_type character The type of output to view result, can be "sjTable", "DT" or "kable"
#' @param save logical Whether output should be saved
#' @param path character Path to the saved output file
#' 
#' @importFrom stats lm
#' @importFrom sjPlot tab_model
#' @importFrom DT datatable
#' @importFrom knitr kable
#' @importFrom broom tidy
#' @importFrom readr write_rds
#' @importFrom glue glue
#'
#' @return table The summarised regression info
#' @export
regress_dataset <- function(data, view_type = c("sjTable","kable","DT"), save = FALSE, path = "lm_params.rds") {
  
  view_type = match.arg(view_type)
  
  # perform linear regression
  reg <- lm(data = data)

  # save
  if (isTRUE(save)) {
    message(glue("Saving output in {path}"))
    write_rds(x = tidy(reg), file = path)
  }
  
  # show
  if (view_type == "DT") {
    reg <- reg %>% tidy() %>% datatable()
  } else if (view_type == "kable") {
    reg <- reg %>% tidy() %>% kable()
  } else if (view_type == "sjTable") {
    reg <- reg %>% tab_model()
  }
  
  return(reg)
}
```

```{r examples-regress_dataset}
data <- fetch_dataset(type = "penguin")
reg <- regress_dataset(data = data, view_type = "sjTable")
reg
```

```{r tests-regress_dataset}
test_that("regress_dataset works", {
  tmp_output <- tempfile(pattern = "regression")
  dir.create(tmp_output)
  
  data <- fetch_dataset(type = "penguin")
  
  reg_dt <- regress_dataset(data = data, view_type = "DT")
  reg_sj <- regress_dataset(data = data, view_type = "sjTable")
  reg_kb <- regress_dataset(data = data, view_type = "kable", save = TRUE, path = file.path(tmp_output, "lm_params.rds"))
  
  expect_s3_class(object = reg_dt,
                  class = c("datatables", "htmlwidget")
                  )

  expect_s3_class(object = reg_sj,
                  class = "sjTable"
                  )
  
  expect_s3_class(object = reg_kb,
                  class = c("knitr_kable")
                  )
  
  expect_true(file.exists(file.path(tmp_output, "lm_params.rds")))
  unlink(tmp_output, recursive = TRUE)

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_regress_dataset.Rmd", vignette_name = "Regress dataset", check = FALSE)
```

