---
title: "flat_plot_dataset.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# `plot_dataset()` : show dataset as graphic

```{r function-plot_dataset}
#' plot_dataset
#'
#' @param data data.frame The data to plot, must have x and y numeric columns
#' @param type character The type of graph to return, either "plotly" or "ggplot"
#' @param candy logical Should the plot have some candy flavour added
#' @param title character Plot title
#' 
#' @importFrom ggplot2 ggplot aes geom_point theme_void labs annotation_raster
#' @importFrom plotly plot_ly
#' @importFrom ggthemes theme_pander
#' @importFrom RSkittleBrewer RSkittleBrewer
#' @importFrom stringr str_to_title
#' @importFrom png readPNG
#' 
#' @return ggplot
#' @export
plot_dataset <- function(data,
                         type = c("ggplot", "plotly"),
                         candy = FALSE,
                         title = "") {
  # get type
  type <- match.arg(type)
  
  # make plot
  if (type == "ggplot") {
    p <- ggplot(data, aes(x = x, y = y)) +
      labs(x = "x", y = "y", title = str_to_title(title))
    
    if (isTRUE(candy)){
      mypng <- readPNG(system.file("icecream.png", package = "deptrapr"))
      p <- p +
        annotation_raster(mypng, ymin = 0, ymax= 40, xmin = 40, xmax = 60) +
        geom_point(
          size = 3,
          colour = sample(
            RSkittleBrewer(flavor = "smarties"),
            dim(data)[1],
            replace = TRUE
          )
        ) +
        theme_void()
    } else {
      p <- p +
        geom_point(size = 3) +
        theme_pander()
    }

  } else if (type == "plotly") {
    p <- plot_ly(
      data,
      x = ~ x,
      y = ~ y,
      type = "scatter",
      mode   = 'markers',
      marker = list(size = 10)
    )
  }
  
  return(p)
}
```

```{r examples-plot_dataset}
data <- fetch_dataset(type = "dino")
p <- plot_dataset(data,
                  type = "ggplot",
                  candy = TRUE,
                  title = "A candynosaurus")
p
```

```{r tests-plot_dataset}
test_that("plot_dataset works", {
  # load data
  data <- fetch_dataset(type = "dino")

  # test ggplot
  p <- plot_dataset(data, type = "ggplot")
  expect_s3_class(p, c("gg", "ggplot"))
  # test plotly
  p <- plot_dataset(data, type = "plotly")
  expect_s3_class(p, c("plotly", "htmlwidget"))
  
  })
```

# `save_plot()` : save graphic in multiple chosen formats
    
```{r function-save_plot}
#' save_plot
#' 
#' @param plot ggplot A ggplot object to be saved
#' @param ext character A vector of output format, can be multiple of "png", "svg", "jpeg", "pdf"
#' @param path character A path where to save the output
#' @param filename character The filename for the output, extension will be added
#' 
#' @importFrom purrr walk
#' @importFrom ggplot2 ggsave
#' @importFrom glue glue
#'
#' @return None Create output files
#' 
#' @export
save_plot <- function(
    plot,
    ext = c("png", "svg", "jpeg", "pdf"),
    path = "graph_output",
    filename = "output"
    ){
    
  ext <- match.arg(ext, several.ok = TRUE)
  
  # check svglite is installed
  if (! requireNamespace("svglite", quietly = TRUE)) {
    stop("To enable svg export with ggsave(), please install svglite : install.packages('svglite')")
  }
  
  # save all format
  ext %>% walk(
    \(x) ggsave(
      filename = file.path(path, glue("{filename}.{x}")),
      plot = plot,
      device = x)
    )
}
```
  
```{r example-save_plot}
# create temp dir
tmp_path <- tempfile(pattern = "saveplot")
dir.create(tmp_path)
ext <- c("svg","pdf")

data <- fetch_dataset(type = "dino")
p <- plot_dataset(data,
                  type = "ggplot",
                  candy = TRUE,
                  title = "the candynosaurus rex")

save_plot(plot = p,
          filename = "dino",
          ext = ext,
          path = tmp_path
)

# clean
unlink(tmp_path, recursive = TRUE)
```
  
```{r tests-save_plot}
test_that("save_plot works", {
  
  tmp_path <- tempfile(pattern = "saveplot")
  dir.create(tmp_path)
  ext <- c("png", "jpeg")
  
  data <- fetch_dataset(type = "dino")
  p <- plot_dataset(data,
                    type = "ggplot",
                    candy = TRUE,
                    title = "the candynosaurus rex")
  
  save_plot(plot = p,
            filename = "dino",
            ext = ext,
            path = tmp_path
            )
  
  # test files are created
  expected_files <- file.path(tmp_path, glue::glue("dino.{ext}"))
  expect_true(all(file.exists(expected_files)))
  
  # clean
  unlink(tmp_path, recursive = TRUE)
  
})

```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_plot_dataset.Rmd", vignette_name = "Show dataset", check = FALSE)
```
