---
title: "flat_explore_dataset.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tidyverse)
library(datasauRus)
library(palmerpenguins)
library(knitr)
library(kableExtra)
library(skimr)
```


```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# `fetch_dataset()` : load example datasets

This function will load a dataset with two numerical variables, x and y.

```{r function-fetch_dataset}
#' fetch_dataset
#' @param type character Type of dataset to load, can be "dino" or "penguin"
#'
#' @import datasauRus
#' @import palmerpenguins
#' @importFrom dplyr filter select sample_n mutate
#' @importFrom tidyr drop_na
#' @importFrom glue glue
#'
#' @return data.frame A dataset
#' @export
fetch_dataset <- function(
    type = c("dino", "penguin")
    ) {
  
  type = match.arg(type)
  if (isTRUE(type == "dino")) {
    dataset <- datasauRus::datasaurus_dozen %>%
      filter(dataset == "dino") %>%
      select(c(x, y))
    message(glue("Loading {type} dataset"))
  }
  else if (isTRUE(type == "penguin")) {
    dataset <- palmerpenguins::penguins %>%
      mutate(x = flipper_length_mm,
             y = body_mass_g) %>%
      drop_na() %>%
      sample_n(142) %>%
      select(c(x, y))
    message(glue("Loading {type} dataset"))
  }
  return(dataset)
}
```

```{r examples-fetch_dataset}
data <- fetch_dataset(type = "dino")
```

```{r tests-fetch_dataset}
test_that("fetch_dataset works", {
  expect_s3_class(object = fetch_dataset(type = "dino"),
                  class = c("tbl_df", "tbl", "data.frame"))

  expect_s3_class(object = fetch_dataset(type = "penguin"),
                  class = c("tbl_df", "tbl", "data.frame"))

  expect_error(object = fetch_dataset("blabla"),
               regexp = "'arg' should be one of .dino., .penguin.")
})
```

# `show_data()` : Take a quick look at the dataset
    
```{r function-show_data}
#' show_data
#' 
#' @param data data.frame The dataset to show
#' @param view_type character Type of view, show the first rows with "head" or global summary with "skim"
#' 
#' @importFrom knitr kable
#' @importFrom kableExtra kable_styling
#' @importFrom skimr skim
#' @importFrom utils head
#' 
#' @return knitre_kable View the dataset
#' 
#' @export
show_data <- function(data, view_type = c("head", "skim")){
  
  view_type = match.arg(view_type)
  
  if (view_type == "head"){
    selected_view <- data %>% head() %>% kable() %>% kable_styling("striped", position = "left", font_size = 7)
  } else if (view_type == "skim"){
    selected_view <- skim(data) %>% kable() %>% kable_styling("striped", position = "left", font_size = 7)
  }
  
  return(selected_view)
}
```
  
```{r example-show_data}
data <- fetch_dataset(type = "dino")
show_data(data = data, view = "skim")
```
  
```{r tests-show_data}
test_that("show_data works", {
  data <- fetch_dataset(type = "dino")
  output <- show_data(data = data, view = "skim")
  expect_s3_class(object = output,
                  class = c("kableExtra", "knitr_kable")
                  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_explore_dataset.Rmd", vignette_name = "Explore datasets", check = FALSE)
```
