# WARNING - Generated by {fusen} from dev/flat_plot_dataset.Rmd: do not edit by hand

test_that("save_plot works", {
  
  tmp_path <- tempfile(pattern = "saveplot")
  dir.create(tmp_path)
  ext <- c("png", "jpeg")
  
  data <- fetch_dataset(type = "dino")
  p <- plot_dataset(data,
                    type = "ggplot",
                    candy = TRUE,
                    title = "the candynosaurus rex")
  
  save_plot(plot = p,
            filename = "dino",
            ext = ext,
            path = tmp_path
            )
  
  # test files are created
  expected_files <- file.path(tmp_path, glue::glue("dino.{ext}"))
  expect_true(all(file.exists(expected_files)))
  
  # clean
  unlink(tmp_path, recursive = TRUE)
  
})

