# WARNING - Generated by {fusen} from dev/flat_plot_dataset.Rmd: do not edit by hand

#' save_plot
#' 
#' @param plot ggplot A ggplot object to be saved
#' @param ext character A vector of output format, can be multiple of "png", "svg", "jpeg", "pdf"
#' @param path character A path where to save the output
#' @param filename character The filename for the output, extension will be added
#' 
#' @importFrom purrr walk
#' @importFrom ggplot2 ggsave
#' @importFrom glue glue
#'
#' @return None Create output files
#' 
#' @export
#' @examples
#' # create temp dir
#' tmp_path <- tempfile(pattern = "saveplot")
#' dir.create(tmp_path)
#' ext <- c("svg","pdf")
#' 
#' data <- fetch_dataset(type = "dino")
#' p <- plot_dataset(data,
#'                   type = "ggplot",
#'                   candy = TRUE,
#'                   title = "the candynosaurus rex")
#' 
#' save_plot(plot = p,
#'           filename = "dino",
#'           ext = ext,
#'           path = tmp_path
#' )
#' 
#' # clean
#' unlink(tmp_path, recursive = TRUE)
save_plot <- function(
    plot,
    ext = c("png", "svg", "jpeg", "pdf"),
    path = "graph_output",
    filename = "output"
    ){
    
  ext <- match.arg(ext, several.ok = TRUE)
  
  # check svglite is installed
  if (! requireNamespace("svglite", quietly = TRUE)) {
    stop("To enable svg export with ggsave(), please install svglite : install.packages('svglite')")
  }
  
  # save all format
  ext %>% walk(
    \(x) ggsave(
      filename = file.path(path, glue("{filename}.{x}")),
      plot = plot,
      device = x)
    )
}
