# WARNING - Generated by {fusen} from dev/flat_plot_dataset.Rmd: do not edit by hand

#' save_plot
#' 
#' @param plot ggplot A ggplot object to be saved
#' @param ext character A vector of output format, can be multiple of "png", "svg", "jpeg", "pdf"
#' @param path character A path where to save the output, will be created if it does not exist
#' @param filename character The filename fo rthe output, extension will be added
#' 
#' @importFrom fs dir_create
#' @importFrom purrr walk
#' @importFrom ggplot2 ggsave
#' @importFrom glue glue
#'
#' @return None Create output files
#' 
#' @export
#' @examples
#' \dontrun{
#' save_plot(plot = p,
#'           filename = "dino")
#' }
save_plot <- function(
    plot,
    ext = c("png", "svg", "jpeg", "pdf"),
    path = "graph_output",
    filename = "output"
    ){
    
  ext <- match.arg(ext, several.ok = TRUE)
  
  # setup output dir
  dir_create(path)
  
  # save all format
  ext %>% walk(
    \(x) ggsave(
      filename = file.path(path, glue("{filename}.{x}")),
      plot = plot,
      device = x)
    )

}
