# WARNING - Generated by {fusen} from dev/flat_explore_dataset.Rmd: do not edit by hand

#' show_data
#' 
#' @param data data.frame The dataset to show
#' @param view_type character Type of view, show the first rows with "head" or global summary with "skim"
#' 
#' @importFrom knitr kable
#' @importFrom skimr skim
#' @importFrom utils head
#' 
#' @return knitre_kable View the dataset
#' 
#' @export
#' @examples
#' data <- fetch_dataset(type = "dino")
#' show_data(data = data, view = "skim")
show_data <- function(data, view_type = c("head", "skim")){
  
  view_type = match.arg(view_type)
  
  if (view_type == "head"){
    selected_view <- data %>% head() %>% kable()
  } else if (view_type == "skim"){
    selected_view <- skim(data) %>% kable()
  }
  
  return(selected_view)
}
